version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: .Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sharedNetwork
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: .Dockerfile
    ports:
      - "8501:8501"
    networks:
      - sharedNetwork
    environment:
      - SERVICE_URL=http://backend:8000/send-query/

networks:
  sharedNetwork:
    driver: bridge
