version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: .Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sharedNetwork
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: .Dockerfile
    ports:
      - "8501:8501"
    networks:
      - sharedNetwork
    environment:
      - LOCALHOST=http://backend:8000
    env_file:
      - .env
    command: streamlit run app.py

networks:
  sharedNetwork:
    driver: bridge
